##### TERMINAL / COLOR #####
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g allow-passthrough on

set-option -g default-shell /usr/bin/zsh
set-option -g default-command /usr/bin/zsh

##### PREFIX #####
unbind C-b
set -g prefix C-s

##### PLUGINS #####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux#v2.1.2' # Latest Catppuccin version
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'

##### CATPPUCCIN CONFIG #####
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_date_time_text " %d-%m %H:%M"

# Leave columns empty for a clean look or add your modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -gF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_date_time}"
set -agF status-right "#{E:@catppuccin_status_battery}"

##### MOUSE #####
set -g mouse on

##### WINDOW / TITLE #####
set -g base-index 1
set -g renumber-windows on

##### COPY MODE (VI) #####
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

##### PANE NAVIGATION (VIM) #####
bind -r ^ last-window
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

##### UTIL #####
bind-key -r f run-shell "tmux neww tmux-sessionizer"

##### PLUGIN RUN #####
# Initialize TMUX plugin manager (keep this at the very bottom)
run ~/.tmux/plugins/tmux-cpu/cpu.tmux
run ~/.tmux/plugins/tmux-battery/battery.tmux
run '~/.tmux/plugins/tpm/tpm'
