-- Generated by nwg-displays on 2026-09-02 at 13:06:22. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@120.0",
    position = "0x0",
    scale = 1,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1280x1024@75.03",
    position = "1920x56",
    scale = 1,
    vrr = 0
})
