#!/bin/bash

MODE="$1"
DIR="$HOME/Pictures/Screenshots"
mkdir -p "$DIR"

FILE="$DIR/screenshot-$(date +%Y-%m-%d_%H-%M-%S).png"

if [ "$MODE" = "region" ]; then
  GEOM=$(slurp) || exit 0 # If selection canceled, exit silently
  grim -g "$GEOM" - | tee "$FILE" | wl-copy
else
  grim - | tee "$FILE" | wl-copy
fi

# Only notify if screenshot succeeded
if [ $? -eq 0 ]; then
  notify-send "Screenshot saved & copied" "$FILE"
fi
